# Generated by Django 4.2.16 on 2024-11-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingproduct',
            name='comparison_disclosure_date',
            field=models.CharField(max_length=100),
        ),
    ]
