# Generated by Django 4.2.16 on 2024-11-19 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings', '0002_alter_savingproduct_comparison_disclosure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingproduct',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_savings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savingproduct',
            name='owned_by',
            field=models.ManyToManyField(blank=True, related_name='owned_savings', to=settings.AUTH_USER_MODEL),
        ),
    ]
