# Generated by Django 4.2.16 on 2024-11-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='privacy_setting',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('subscriber', 'Subscriber')], max_length=20),
        ),
    ]
