# Generated by Django 4.2.16 on 2024-11-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_alter_post_image_delete_commnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_user_pk',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
