# Generated by Django 4.2.16 on 2024-11-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assets',
            field=models.IntegerField(default=0),
        ),
    ]
